import { createContext, useContext, useMemo, useState } from 'react';

const JobsContext = createContext(null);

const initialJobs = [
  {
    id: 'WO-25-01-0001',
    title: 'เปลี่ยนคอมเพรสเซอร์แอร์ห้องประชุม',
    desc: 'สำนักงานใหญ่ - On-site',
    badge: 'Urgent',
    status: 'new',
    customer: 'บริษัท A',
    type: 'MA',
    department: 'IT Support',
    version: 'v1',
    priority: 'สูง (Critical)',
    openedAt: '2025-11-20T09:00:00',
    dueDate: '2025-11-24T16:00:00',
    location: '13.855642274086346, 100.58548532919454',
    locationAddress: 'ชั้น 12 อาคาร11 มหาวิทยาลัยศรีปทุม',
    mapUrl: 'https://maps.google.com/?q=13.855642274086346,100.58548532919454',
    contactPerson: 'คุณเอ',
    contactPhone: '0800000001',
    address: '99/1 ถนนแจ้งวัฒนะ กรุงเทพฯ',
    requirementDetail: 'ตรวจสอบและเปลี่ยนคอมเพรสเซอร์แอร์ห้องประชุม',
    mainTechnician: 'ช่างเอก',
    assistantTechnicians: 'ช่างบอย',
    checkInAt: '2025-11-24T13:00:00',
    checkOutAt: '2025-11-24T16:30:00',
    workLogBefore: 'แอร์ไม่เย็น มีเสียงดัง',
    workLogAction: 'ถอดคอมเพรสเซอร์เดิมและติดตั้งใหม่',
    workLogTest: 'ทดสอบเดินระบบ 30 นาที อุณหภูมิคงที่',
    resultStatus: 'สำเร็จสมบูรณ์',
    resultSummary: 'เปลี่ยนคอมเพรสเซอร์สำเร็จ ระบบปกติ',
    followUpTask: 'ตรวจเช็คอีกครั้งใน 7 วัน',
    technicianNote: 'ควรล้างแอร์รอบหน้า',
    supervisorNote: 'อนุมัติปิดงาน',
    customerSignName: 'คุณสมหญิง',
    customerSignTitle: 'ผู้จัดการอาคาร',
    customerSignDate: '2025-11-24',
    supervisorCloseName: 'หัวหน้าช่างเอก',
    supervisorCloseDate: '2025-11-24',
    supervisorCloseStatus: 'อนุมัติ',
    supervisorCloseReason: '',
    technicians: [
      { id: 'tech01', name: 'ช่างเอก' },
      { id: 'tech02', name: 'ช่างบอย' },
    ],
  },
  {
    id: 'WO-25-02-0002',
    title: 'ตรวจเช็คระบบไฟฟ้าชั้น 12',
    desc: 'สำนักงานใหญ่ - On-site',
    badge: 'Follow-up',
    status: 'in_progress',
    customer: 'บริษัท B',
    type: 'Per-call',
    department: 'Facility',
    version: 'v2',
    priority: 'กลาง (Normal)',
    openedAt: '2025-11-21T10:00:00',
    dueDate: '2025-11-26T10:00:00',
    location: '13.7584, 100.5040',
    locationAddress: 'ชั้น 12 อาคาร11 มหาวิทยาลัยศรีปทุม',
    mapUrl: 'https://maps.google.com/?q=13.7584,100.5040',
    contactPerson: 'คุณบี',
    contactPhone: '0800000002',
    address: 'ชั้น 12 อาคารสำนักงานใหญ่',
    requirementDetail: 'ตรวจเช็คระบบไฟฟ้าและเบรกเกอร์',
    mainTechnician: 'ช่างก้อง',
    assistantTechnicians: '',
    checkInAt: '2025-11-25T09:00:00',
    checkOutAt: '',
    workLogBefore: 'ไฟตกเป็นระยะ',
    workLogAction: 'วัดโหลด เปลี่ยนเบรกเกอร์',
    workLogTest: 'ทดสอบโหลดปกติ',
    resultStatus: 'สำเร็จบางส่วน',
    resultSummary: 'แก้ไขแล้ว เหลือติดตั้ง Surge Protector',
    followUpTask: 'ติดตั้ง Surge Protector สัปดาห์หน้า',
    technicianNote: '',
    supervisorNote: '',
    customerSignName: '',
    customerSignTitle: '',
    customerSignDate: '',
    supervisorCloseName: '',
    supervisorCloseDate: '',
    supervisorCloseStatus: '',
    supervisorCloseReason: '',
    technicians: [{ id: 'tech03', name: 'ช่างก้อง' }],
  },

  {
    id: 'WO-25-02-0006',
    title: 'ตรวจเช็คระบบไฟฟ้าชั้น 13',
    desc: 'สำนักงานใหญ่ - On-site',
    badge: 'Follow-up',
    status: 'in_progress',
    customer: 'บริษัท c',
    type: 'Per-call',
    department: 'Facility',
    version: 'v1',
    priority: 'กลาง (Normal)',
    openedAt: '2025-11-22T11:00:00',
    dueDate: '2025-11-26T10:00:00',
    location: '13.7584, 100.5040',
    locationAddress: 'ชั้น 12 อาคาร11 มหาวิทยาลัยศรีปทุม',
    mapUrl: 'https://maps.google.com/?q=13.7584,100.5040',
    contactPerson: 'คุณซี',
    contactPhone: '0800000003',
    address: 'ชั้น 13 อาคารสำนักงานใหญ่',
    requirementDetail: 'ตรวจเช็คระบบไฟฟ้าชั้น 13',
    mainTechnician: 'ช่างก้อง',
    assistantTechnicians: '',
    checkInAt: '',
    checkOutAt: '',
    workLogBefore: '',
    workLogAction: '',
    workLogTest: '',
    resultStatus: 'สำเร็จบางส่วน',
    resultSummary: '',
    followUpTask: '',
    technicianNote: '',
    supervisorNote: '',
    technicians: [{ id: 'tech03', name: 'ช่างก้อง' }],
  },

  {
    id: 'WO-25-03-0003',
    title: 'ทดสอบระบบกล้องวงจรปิด',
    desc: 'สาขาบางนา - Remote',
    badge: 'Review',
    status: 'done',
    customer: 'บริษัท C',
    type: 'Project',
    department: 'Security',
    version: 'v1',
    priority: 'ต่ำ (Low)',
    openedAt: '2025-11-15T08:00:00',
    dueDate: '2025-11-20T09:00:00',
    location: '13.6691, 100.6342',
    locationAddress: 'สาขาบางนา - Remote',
    mapUrl: 'https://maps.google.com/?q=13.6691,100.6342',
    contactPerson: 'คุณดี',
    contactPhone: '0800000004',
    address: 'สาขาบางนา',
    requirementDetail: 'ทดสอบระบบกล้องและบันทึก',
    mainTechnician: 'ช่างบอย',
    assistantTechnicians: '',
    checkInAt: '2025-11-19T10:00:00',
    checkOutAt: '2025-11-19T15:00:00',
    workLogBefore: 'กล้องบางตัวภาพไม่ขึ้น',
    workLogAction: 'รีเซ็ต ตั้งค่าใหม่ อัปเดตเฟิร์มแวร์',
    workLogTest: 'ภาพขึ้นครบ ระบบบันทึกปกติ',
    resultStatus: 'สำเร็จสมบูรณ์',
    resultSummary: 'กล้องใช้งานได้ครบทุกตัว',
    followUpTask: 'ตรวจเช็คซ้ำ 1 เดือน',
    technicianNote: '',
    supervisorNote: '',
    customerSignName: 'คุณอารี',
    customerSignTitle: 'ผู้จัดการสาขา',
    customerSignDate: '2025-11-19',
    supervisorCloseName: 'หัวหน้าช่างบอย',
    supervisorCloseDate: '2025-11-19',
    supervisorCloseStatus: 'อนุมัติ',
    supervisorCloseReason: '',
    technicians: [{ id: 'tech02', name: 'ช่างบอย' }],
  },
  {
    id: 'WO-25-01-0004',
    title: 'อัปเดตซอฟต์แวร์เครื่องแม่ข่าย',
    desc: 'ดาต้าเซ็นเตอร์ - Remote',
    badge: 'Delayed',
    status: 'rejected',
    customer: 'บริษัท D',
    type: 'MA',
    department: 'IT Ops',
    version: 'v3',
    priority: 'สูง (Critical)',
    openedAt: '2025-11-18T11:00:00',
    dueDate: '2025-11-28T18:00:00',
    location: '13.78, 100.55',
    locationAddress: 'ดาต้าเซ็นเตอร์',
    mapUrl: 'https://maps.google.com/?q=13.78,100.55',
    contactPerson: 'คุณอี',
    contactPhone: '0800000005',
    address: 'ดาต้าเซ็นเตอร์',
    requirementDetail: 'อัปเดต OS และแพตช์ความปลอดภัย',
    mainTechnician: 'ช่างเก่ง',
    assistantTechnicians: '',
    checkInAt: '',
    checkOutAt: '',
    workLogBefore: 'ต้องการอัปเดตแพตช์',
    workLogAction: 'ยกเลิกโดยลูกค้า',
    workLogTest: '',
    resultStatus: 'ไม่สำเร็จ',
    resultSummary: 'ลูกค้ายกเลิก',
    followUpTask: 'รอคิวใหม่',
    technicianNote: '',
    supervisorNote: '',
    customerSignName: '',
    customerSignTitle: '',
    customerSignDate: '',
    supervisorCloseName: '',
    supervisorCloseDate: '',
    supervisorCloseStatus: 'ตีกลับให้แก้ไข',
    supervisorCloseReason: 'ลูกค้ายกเลิกกะทันหัน',
    technicians: [{ id: 'tech04', name: 'ช่างเก่ง' }],
  },
  {
    id: 'WO-25-02-0005',
    title: 'ยกเลิกงานตรวจสอบสายสื่อสาร',
    desc: 'สำนักงานใหญ่ - On-site',
    badge: 'Canceled',
    status: 'canceled',
    customer: 'บริษัท E',
    type: 'Per-call',
    department: 'Network',
    version: 'v1',
    priority: 'ต่ำ (Low)',
    openedAt: '2025-11-10T08:00:00',
    dueDate: '2025-11-30T09:00:00',
    location: '13.745, 100.532',
    locationAddress: 'สำนักงานใหญ่ - On-site',
    mapUrl: 'https://maps.google.com/?q=13.745,100.532',
    contactPerson: 'คุณเอฟ',
    contactPhone: '0800000006',
    address: 'สำนักงานใหญ่ ถนนพระราม 6',
    requirementDetail: 'ตรวจสอบสายสื่อสาร (ยกเลิก)',
    mainTechnician: '',
    assistantTechnicians: '',
    checkInAt: '',
    checkOutAt: '',
    workLogBefore: '',
    workLogAction: '',
    workLogTest: '',
    resultStatus: 'ไม่สำเร็จ',
    resultSummary: 'งานถูกยกเลิก',
    followUpTask: '',
    technicianNote: '',
    supervisorNote: '',
    customerSignName: '',
    customerSignTitle: '',
    customerSignDate: '',
    supervisorCloseName: '',
    supervisorCloseDate: '',
    supervisorCloseStatus: 'ตีกลับให้แก้ไข',
    supervisorCloseReason: 'ยกเลิกงาน',
    technicians: [],
  },
];

export function JobsProvider({ children }) {
  const [jobs, setJobs] = useState(initialJobs);

  const updateJobStatus = (id, newStatus) => {
    setJobs((prev) =>
      prev.map((job) => (job.id === id ? { ...job, status: newStatus } : job)),
    );
  };

  const assignTechnicians = (id, technicians) => {
    setJobs((prev) =>
      prev.map((job) =>
        job.id === id ? { ...job, technicians } : job,
      ),
    );
  };

  const value = useMemo(
    () => ({ jobs, updateJobStatus, assignTechnicians }),
    [jobs],
  );

  return <JobsContext.Provider value={value}>{children}</JobsContext.Provider>;
}

export function useJobs() {
  const ctx = useContext(JobsContext);
  if (!ctx) {
    throw new Error('useJobs must be used within JobsProvider');
  }
  return ctx;
}
